name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      variant:
        description: "Build variant"
        type: choice
        options: [debug, release]
        default: debug
        required: true
      artifact_type:
        description: "What to build"
        type: choice
        options: [apk, aab]
        default: apk
        required: true
      run_lint:
        description: "Run Android Lint?"
        type: boolean
        default: true
      run_tests:
        description: "Run unit tests?"
        type: boolean
        default: true
      gradle_args:
        description: "Extra Gradle args (optional)"
        type: string
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '17'
      APP_MODULE: app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      # Determine inputs or sensible defaults when triggered by push/PR
      - name: Resolve inputs
        id: cfg
        shell: bash
        run: |
          # Variant
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.variant }}" ]]; then
            VARIANT="${{ github.event.inputs.variant }}"
          else
            VARIANT="debug"
          fi
          echo "variant=$VARIANT" >> "$GITHUB_OUTPUT"

          # Artifact type
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.artifact_type }}" ]]; then
            ARTIFACT_TYPE="${{ github.event.inputs.artifact_type }}"
          else
            ARTIFACT_TYPE="apk"
          fi
          echo "artifact_type=$ARTIFACT_TYPE" >> "$GITHUB_OUTPUT"

          # Lint/tests flags
          RUN_LINT="${{ github.event.inputs.run_lint || 'true' }}"
          RUN_TESTS="${{ github.event.inputs.run_tests || 'true' }}"
          echo "run_lint=$RUN_LINT" >> "$GITHUB_OUTPUT"
          echo "run_tests=$RUN_TESTS" >> "$GITHUB_OUTPUT"

          # Extra args
          EXTRA_ARGS="${{ github.event.inputs.gradle_args }}"
          echo "gradle_args=$EXTRA_ARGS" >> "$GITHUB_OUTPUT"

      - name: Build
        run: |
          set -e
          VARIANT="${{ steps.cfg.outputs.variant }}"
          TYPE="${{ steps.cfg.outputs.artifact_type }}"
          EXTRA="${{ steps.cfg.outputs.gradle_args }}"

          if [[ "$TYPE" == "aab" && "$VARIANT" == "debug" ]]; then
            echo "AAB is typically for release; building debug APK instead for convenience."
            TYPE="apk"
          fi

          if [[ "$TYPE" == "apk" ]]; then
            TASK="assemble${VARIANT^}"
          else
            TASK="bundleRelease"
          fi

          echo "Running: ./gradlew $TASK $EXTRA"
          ./gradlew $TASK $EXTRA --stacktrace

      - name: Lint
        if: ${{ steps.cfg.outputs.run_lint == 'true' }}
        run: ./gradlew lint${{ steps.cfg.outputs.variant == 'release' && 'Release' || 'Debug' }} --stacktrace

      - name: Unit tests
        if: ${{ steps.cfg.outputs.run_tests == 'true' }}
        run: ./gradlew test${{ steps.cfg.outputs.variant == 'release' && 'Release' || 'Debug' }}UnitTest --stacktrace

      - name: Upload APK artifact (if built)
        if: ${{ steps.cfg.outputs.artifact_type == 'apk' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ steps.cfg.outputs.variant }}-apk
          path: ${{ env.APP_MODULE }}/build/outputs/apk/${{ steps.cfg.outputs.variant }}/*.apk

      - name: Upload AAB artifact (if built)
        if: ${{ steps.cfg.outputs.artifact_type == 'aab' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: ${{ env.APP_MODULE }}/build/outputs/bundle/release/*.aab

      - name: Upload Lint Report
        if: ${{ always() && steps.cfg.outputs.run_lint == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: lint-report-${{ steps.cfg.outputs.variant }}
          path: ${{ env.APP_MODULE }}/build/reports/lint-results-${{ steps.cfg.outputs.variant }}.html
