name: Release APK

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: {}
# (rest of the file unchanged)


jobs:
  release-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Release (unsigned)
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload APK (Release, unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned-apk
          path: app/build/outputs/apk/release/*.apk
