name: Release APK

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: {}

jobs:
  release-apk:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '17'
      WRAPPER_GRADLE_VERSION: '8.7'
      GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx3g -XX:MaxMetaspaceSize=1g' -Dorg.gradle.warning.mode=all"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Ensure Gradle Wrapper (auto-install Gradle if missing)
        run: |
          set -e
          if [[ ! -f gradlew ]]; then
            curl -s https://get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle $WRAPPER_GRADLE_VERSION
            gradle wrapper --gradle-version $WRAPPER_GRADLE_VERSION
          fi
          chmod +x gradlew

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # 🩺 Sanity check
      - name: Gradle sanity check (help & versions)
        continue-on-error: true
        run: |
          ./gradlew --version
          ./gradlew help -S

      - name: Build Release (unsigned)
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload APK (Release, unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned-apk
          path: app/build/outputs/apk/release/*.apk
